##########################################################
# Replica Configuration
##########################################################

replicaCount: 1

##########################################################
# Container Image
##########################################################

image:
  repository: asia-south1-docker.pkg.dev/vishnu-cloud-lab/gitops-images/gitops-demo
  tag: "393360c124c7f54c780926fffc223c43513c5e88"
  pullPolicy: Always

##########################################################
# Service
##########################################################

service:
  type: ClusterIP
  port: 80
  targetPort: 80

##########################################################
# Container Port
##########################################################

containerPort: 80

##########################################################
# Resources
##########################################################

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"

  limits:
    cpu: "100m"
    memory: "128Mi"

##########################################################
# Service Account
##########################################################

serviceAccount:
  create: true
  name: ""

##########################################################
# Ingress
##########################################################

##########################################################
# Ingress
##########################################################

ingress:
  enabled: true

  className: nginx

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  hosts:
    - host: app.vishnupochampalli.work.gd
      paths:
        - path: /
          pathType: Prefix

  tls:
    - secretName: gitops-prod-tls
      hosts:
        - app.vishnupochampalli.work.gd

##########################################################
# Autoscaling
##########################################################

autoscaling:
  enabled: false

##########################################################
# Node Selector
##########################################################

nodeSelector: {}

##########################################################
# Tolerations
##########################################################

tolerations: []

##########################################################
# Affinity
##########################################################

affinity: {}