##########################################################
# Replica Configuration
##########################################################

replicaCount: 1

##########################################################
# Container Image
##########################################################

image:
  repository: asia-south1-docker.pkg.dev/vishnu-cloud-lab/gitops-images/gitops-demo
  tag: "latest"
  pullPolicy: IfNotPresent

##########################################################
# Service
##########################################################

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

##########################################################
# Container Port
##########################################################

containerPort: 80

##########################################################
# Resources
##########################################################

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"

  limits:
    cpu: "100m"
    memory: "128Mi"

##########################################################
# Service Account
##########################################################

serviceAccount:
  create: true
  name: ""

##########################################################
# Ingress
##########################################################

ingress:
  enabled: false

##########################################################
# Autoscaling
##########################################################

autoscaling:
  enabled: false

##########################################################
# Node Selector
##########################################################

nodeSelector: {}

##########################################################
# Tolerations
##########################################################

tolerations: []

##########################################################
# Affinity
##########################################################

affinity: {}