# refer apps/gitpops-demo.yaml for the application definition of gitops-demo app. This is a root application that will deploy all the applications defined in apps folder.

# apiVersion: argoproj.io/v1alpha1
# kind: Application

# metadata:
#   name: gitops-demo
#   namespace: argocd     

# spec:
#   project: default

#   source:
#     repoURL: https://github.com/vishnupochampelly/gitops-argocd-atlantis.git
#     targetRevision: main
#     path: helm-charts/gitops-demo

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

#     syncOptions:
#       - CreateNamespace=true