apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: nginx

  rules:
    - host: grafana.vishnupochampalli.work.gd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80

  tls:
    - hosts:
        - grafana.vishnupochampalli.work.gd
      secretName: grafana-prod-tls