apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: gitops-staging-tls
  namespace: default

spec:
  secretName: gitops-staging-tls

  privateKey:
    rotationPolicy: Always

  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

  dnsNames:
    - app.vishnupochampalli.work.gd

#Dummy commmit
    

    
